### ISSUE TITLE
Rails 4.2?

### ISSUE THREAD

**Issue by JensC** [znz/doorkeeper-provider-app#1]
It is a nice and working provider app. However it doesn't work with recent Rails anymore. Any chance to upgrade the app to work with Rails 4.2.
Thanks
Jens

**Comment by znz** [comment]
I updated to Rails 4.2 and updated other gems.

**Comment by JensC** [comment]
Wonderful! I willl check it and give you some feedback soon.

**Comment by JensC** [comment]
Works like a charm now. Thanks again!
